{{ if and (index .Values "modules" "text2vec-huggingface" "enabled") (index .Values "modules" "text2vec-huggingface" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-huggingface
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  apiKey: {{ index .Values "modules" "text2vec-huggingface" "apiKey" | b64enc }}
{{ end }}
