{{-  $t2vVoyageAI := and (index .Values "modules" "text2vec-voyageai" "enabled") (index .Values "modules" "text2vec-voyageai" "apiKey") -}}
{{-  $rerankerVoyageAI := and (index .Values "modules" "reranker-voyageai" "enabled") (index .Values "modules" "reranker-voyageai" "apiKey") }}
{{-  $multi2vecVoyageAI := and (index .Values "modules" "multi2vec-voyageai" "enabled") (index .Values "modules" "multi2vec-voyageai" "apiKey") }}
{{-  $voyageai := or ($t2vVoyageAI) ($rerankerVoyageAI) ($multi2vecVoyageAI) }}
{{- if $voyageai }}

{{- $apiKeys := list }}
{{- if $t2vVoyageAI }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "text2vec-voyageai" "apiKey") -}}
{{- end }}
{{- if $rerankerVoyageAI }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "reranker-voyageai" "apiKey") -}}
{{- end }}
{{- if $multi2vecVoyageAI }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "multi2vec-voyageai" "apiKey") -}}
{{- end }}

{{- if gt (len ($apiKeys | uniq)) 1 -}}
  {{- fail "VoyageAI modules activated, but their keys differ. Use the same key on all activated VoyageAI modules." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: weaviate-voyageai
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if (index .Values "modules" "reranker-voyageai" "apiKey") }}
  apiKey: {{ index .Values "modules" "reranker-voyageai" "apiKey" | b64enc }}
  {{- else if (index .Values "modules" "multi2vec-voyageai" "apiKey") }}
  apiKey: {{ index .Values "modules" "multi2vec-voyageai" "apiKey" | b64enc }}
  {{- else }}
  apiKey: {{ index .Values "modules" "text2vec-voyageai" "apiKey" | b64enc }}
  {{- end }}
{{ end }}
