{{-  $t2vPaLM := and (index .Values "modules" "text2vec-palm" "enabled") (index .Values "modules" "text2vec-palm" "apiKey") -}}
{{-  $generativePaLM := and (index .Values "modules" "generative-palm" "enabled") (index .Values "modules" "generative-palm" "apiKey") }}
{{-  $m2vPaLM := and (index .Values "modules" "multi2vec-palm" "enabled") (index .Values "modules" "multi2vec-palm" "apiKey") -}}
{{-  $palm := or ($t2vPaLM) ($generativePaLM) ($m2vPaLM) }}
{{- if $palm }}

{{- $apiKeys := list }}
{{- if $t2vPaLM }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "text2vec-palm" "apiKey") -}}
{{- end }}
{{- if $generativePaLM }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "generative-palm" "apiKey") -}}
{{- end }}
{{- if $m2vPaLM }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "multi2vec-palm" "apiKey") -}}
{{- end }}

{{- if gt (len ($apiKeys | uniq)) 1 -}}
  {{- fail "Google PaLM modules activated, but their keys differ. Use the same key on all activated Google PaLM modules." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: weaviate-palm
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if (index .Values "modules" "generative-palm" "apiKey") }}
  apiKey: {{ index .Values "modules" "generative-palm" "apiKey" | b64enc }}
  {{- else if (index .Values "modules" "multi2vec-palm" "apiKey") }}
  apiKey: {{ index .Values "modules" "multi2vec-palm" "apiKey" | b64enc }}
  {{- else }}
  apiKey: {{ index .Values "modules" "text2vec-palm" "apiKey" | b64enc }}
  {{- end }}
{{ end }}
