{{-  $t2vCohere := and (index .Values "modules" "text2vec-cohere" "enabled") (index .Values "modules" "text2vec-cohere" "apiKey") -}}
{{-  $generativeCohere := and (index .Values "modules" "generative-cohere" "enabled") (index .Values "modules" "generative-cohere" "apiKey") }}
{{-  $rerankerCohere := and (index .Values "modules" "reranker-cohere" "enabled") (index .Values "modules" "reranker-cohere" "apiKey") }}
{{-  $multi2vecCohere := and (index .Values "modules" "multi2vec-cohere" "enabled") (index .Values "modules" "multi2vec-cohere" "apiKey") }}
{{-  $cohere := or ($t2vCohere) ($generativeCohere) ($rerankerCohere) ($multi2vecCohere) }}
{{- if $cohere }}

{{- $apiKeys := list }}
{{- if $t2vCohere }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "text2vec-cohere" "apiKey") -}}
{{- end }}
{{- if $generativeCohere }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "generative-cohere" "apiKey") -}}
{{- end }}
{{- if $rerankerCohere }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "reranker-cohere" "apiKey") -}}
{{- end }}
{{- if $multi2vecCohere }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "multi2vec-cohere" "apiKey") -}}
{{- end }}

{{- if gt (len ($apiKeys | uniq)) 1 -}}
  {{- fail "Cohere modules activated, but their keys differ. Use the same key on all activated Cohere modules." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: weaviate-cohere
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if (index .Values "modules" "generative-cohere" "apiKey") }}
  apiKey: {{ index .Values "modules" "generative-cohere" "apiKey" | b64enc }}
  {{- else if (index .Values "modules" "reranker-cohere" "apiKey") }}
  apiKey: {{ index .Values "modules" "reranker-cohere" "apiKey" | b64enc }}
  {{- else if (index .Values "modules" "multi2vec-cohere" "apiKey") }}
  apiKey: {{ index .Values "modules" "multi2vec-cohere" "apiKey" | b64enc }}
  {{- else }}
  apiKey: {{ index .Values "modules" "text2vec-cohere" "apiKey" | b64enc }}
  {{- end }}
{{ end }}
