{{ if and (index .Values "modules" "text2vec-digitalocean" "enabled") (index .Values "modules" "text2vec-digitalocean" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-digitalocean
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  apiKey: {{ index .Values "modules" "text2vec-digitalocean" "apiKey" | b64enc }}
{{ end }}
