{{-  $t2vGoogle := and (index .Values "modules" "text2vec-google" "enabled") (index .Values "modules" "text2vec-google" "apiKey") -}}
{{-  $generativeGoogle := and (index .Values "modules" "generative-google" "enabled") (index .Values "modules" "generative-google" "apiKey") }}
{{-  $m2vGoogle := and (index .Values "modules" "multi2vec-google" "enabled") (index .Values "modules" "multi2vec-google" "apiKey") -}}
{{-  $google := or ($t2vGoogle) ($generativeGoogle) ($m2vGoogle) }}
{{- if $google }}

{{- $apiKeys := list }}
{{- if $t2vGoogle }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "text2vec-google" "apiKey") -}}
{{- end }}
{{- if $generativeGoogle }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "generative-google" "apiKey") -}}
{{- end }}
{{- if $m2vGoogle }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "multi2vec-google" "apiKey") -}}
{{- end }}

{{- if gt (len ($apiKeys | uniq)) 1 -}}
  {{- fail "Google modules activated, but their keys differ. Use the same key on all activated Google modules." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: weaviate-google
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if (index .Values "modules" "generative-google" "apiKey") }}
  apiKey: {{ index .Values "modules" "generative-google" "apiKey" | b64enc }}
  {{- else if (index .Values "modules" "multi2vec-google" "apiKey") }}
  apiKey: {{ index .Values "modules" "multi2vec-google" "apiKey" | b64enc }}
  {{- else }}
  apiKey: {{ index .Values "modules" "text2vec-google" "apiKey" | b64enc }}
  {{- end }}
{{ end }}
