{{-  $t2vOctoAI := and (index .Values "modules" "text2vec-octoai" "enabled") (index .Values "modules" "text2vec-octoai" "apiKey") -}}
{{-  $generativeOctoAI := and (index .Values "modules" "generative-octoai" "enabled") (index .Values "modules" "generative-octoai" "apiKey") }}
{{-  $octoai := or ($t2vOctoAI) ($generativeOctoAI) }}
{{- if $octoai }}

{{- $apiKeys := list }}
{{- if $t2vOctoAI }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "text2vec-octoai" "apiKey") -}}
{{- end }}
{{- if $generativeOctoAI }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "generative-octoai" "apiKey") -}}
{{- end }}

{{- if gt (len ($apiKeys | uniq)) 1 -}}
  {{- fail "OctoAI modules activated, but their keys differ. Use the same key on all activated OctoAI modules." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: weaviate-octoai
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  apiKey: {{ index $apiKeys 0 | b64enc }}
{{ end }}
