{{-  $t2vAWS := and (index .Values "modules" "text2vec-aws" "enabled") (index .Values "modules" "text2vec-aws" "secrets") -}}
{{-  $generativeAWS := and (index .Values "modules" "generative-aws" "enabled") (index .Values "modules" "generative-aws" "secrets") }}
{{-  $backupS3 := and (index .Values "backups" "s3" "enabled") (index .Values "backups" "s3" "secrets") -}}
{{-  $offloadS3 := and (index .Values "offload" "s3" "enabled") (index .Values "offload" "s3" "secrets") -}}
{{-  $awsSecrets := or ($t2vAWS) ($generativeAWS) ($backupS3) ($offloadS3) }}

{{- $awsSecrets := list }}
{{- if $t2vAWS -}}
  {{ $awsSecrets = append $awsSecrets "text2vec-aws" }}
{{- end }}
{{- if $generativeAWS -}}
  {{ $awsSecrets = append $awsSecrets "generative-aws" }}
{{- end }}
{{- if $backupS3 -}}
  {{ $awsSecrets = append $awsSecrets "backup-s3" }}
{{- end }}
{{- if $offloadS3 -}}
  {{ $awsSecrets = append $awsSecrets "offload-s3" }}
{{- end }}

{{- if gt (len $awsSecrets) 1 -}}
  {{- fail "AWS modules activated, but with both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY keys. Please choose one configuration to pass AWS credentials." }}
{{- end }}

{{- if ($awsSecrets) -}}
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-aws
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if index .Values "modules" "text2vec-aws" "secrets" "AWS_ACCESS_KEY_ID" }}
  AWS_ACCESS_KEY_ID: {{ index .Values "modules" "text2vec-aws" "secrets" "AWS_ACCESS_KEY_ID" | b64enc }}
  {{- else if (index .Values "modules" "generative-aws" "secrets" "AWS_ACCESS_KEY_ID") }}
  AWS_ACCESS_KEY_ID: {{ index .Values "modules" "generative-aws" "secrets" "AWS_ACCESS_KEY_ID" | b64enc }}
  {{- else if (index .Values "backups" "s3" "secrets" "AWS_ACCESS_KEY_ID") }}
  AWS_ACCESS_KEY_ID: {{ index .Values "backups" "s3" "secrets" "AWS_ACCESS_KEY_ID" | b64enc }}
  {{- else if (index .Values "offload" "s3" "secrets" "AWS_ACCESS_KEY_ID") }}
  AWS_ACCESS_KEY_ID: {{ index .Values "offload" "s3" "secrets" "AWS_ACCESS_KEY_ID" | b64enc }}
  {{- end }}
  {{- if index .Values "modules" "text2vec-aws" "secrets" "AWS_SECRET_ACCESS_KEY" }}
  AWS_SECRET_ACCESS_KEY: {{ index .Values "modules" "text2vec-aws" "secrets" "AWS_SECRET_ACCESS_KEY" | b64enc }}
  {{- else if (index .Values "modules" "generative-aws" "secrets" "AWS_SECRET_ACCESS_KEY") }}
  AWS_SECRET_ACCESS_KEY: {{ index .Values "modules" "generative-aws" "secrets" "AWS_SECRET_ACCESS_KEY" | b64enc }}
  {{- else if (index .Values "backups" "s3" "secrets" "AWS_SECRET_ACCESS_KEY") }}
  AWS_SECRET_ACCESS_KEY: {{ index .Values "backups" "s3" "secrets" "AWS_SECRET_ACCESS_KEY" | b64enc }}
  {{- else if (index .Values "offload" "s3" "secrets" "AWS_SECRET_ACCESS_KEY") }}
  AWS_SECRET_ACCESS_KEY: {{ index .Values "offload" "s3" "secrets" "AWS_SECRET_ACCESS_KEY" | b64enc }}
  {{- end }}
{{- end }}
