{{- $backup := index .Values "backups" "azure" -}}
{{ if and (index $backup "enabled") (index $backup "secrets") }}
{{- if or (index $backup "secrets" "AZURE_STORAGE_ACCOUNT") (index $backup "secrets" "AZURE_STORAGE_KEY") (index $backup "secrets" "AZURE_STORAGE_CONNECTION_STRING") }}
apiVersion: v1
kind: Secret
metadata:
  name: backup-azure
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if index $backup "secrets" "AZURE_STORAGE_ACCOUNT" }}
  AZURE_STORAGE_ACCOUNT: {{ index $backup "secrets" "AZURE_STORAGE_ACCOUNT" | b64enc }}
  {{- end }}
  {{- if index $backup "secrets" "AZURE_STORAGE_KEY" }}
  AZURE_STORAGE_KEY: {{ index $backup "secrets" "AZURE_STORAGE_KEY" | b64enc }}
  {{- end }}
  {{- if index $backup "secrets" "AZURE_STORAGE_CONNECTION_STRING" }}
  AZURE_STORAGE_CONNECTION_STRING: {{ index $backup "secrets" "AZURE_STORAGE_CONNECTION_STRING" | b64enc }}
  {{- end }}
{{- end }}
{{ end }}
