{{- $backup := index .Values "backups" "gcs" -}}
{{ if and (index $backup "enabled") (index $backup "secrets") }}
{{- if index $backup "secrets" "GOOGLE_APPLICATION_CREDENTIALS" }}
apiVersion: v1
kind: Secret
metadata:
  name: backup-gcs
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  GOOGLE_APPLICATION_CREDENTIALS: {{ index $backup "secrets" "GOOGLE_APPLICATION_CREDENTIALS" | b64enc }}
{{- end }}
{{ end }}
