{{ if .Values.importer }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: weaviate-demo-importer
  name: weaviate-demo-importer
spec:
  template:
    metadata:
      labels:
        app: weaviate-demo-importer
    spec:
      containers:
      - args:
        - -weaviate-url
        - http://weaviate/weaviate/v1/
        image: {{ .Values.image.registry }}creativesoftwarefdn/weaviate-demo-importer:0.0.2
        name: weaviate-demo-importer
      restartPolicy: OnFailure
{{ end }}