{{- $module := index .Values "modules" "multi2vec-clip" -}}
{{ if index $module "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-clip-inference
  labels:
    name: {{ .Release.Name }}-clip-inference
    app: {{ .Release.Name }}-clip-inference
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ index $module "replicas" }}
  strategy:
{{ toYaml (index $module "strategy") | indent 4}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-clip-inference
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-clip-inference
    spec:
      securityContext:
{{ toYaml (index $module "securityContext") | indent 8}}
      {{- if (index $module "serviceAccountName") }}
      serviceAccountName: {{ index $module "serviceAccountName" }}
      {{- else if (index .Values "serviceAccountName") }}
      serviceAccountName: {{ index .Values "serviceAccountName" }}
      {{- end }}
      {{- include "image.pullSecrets" (dict "pullSecrets" (index $module "imagePullSecrets")) | nindent 6 }}
      {{- include "pod.priorityClassName" ( dict "global" $.Values.globalPriorityClassName "priorityClassName" (index $module "priorityClassName")) | nindent 6 }}
      containers:
      - name: {{ .Release.Name }}-clip-inference
        image: {{ index $module "registry" }}/{{ index $module "repo" }}:{{ index $module "tag" }}
        imagePullPolicy: {{ index $module "imagePullPolicy" }}
        env:
          - name: ENABLE_CUDA
            value: "{{ if index $module "envconfig" "enable_cuda" }}1{{ else }}0{{ end }}"
          {{ if index $module "envconfig" "enable_cuda" }}
          - name: NVIDIA_VISIBLE_DEVICES
            value: {{ index $module "envconfig" "nvidia_visible_devices"}}
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: {{ index $module "envconfig" "nvidia_driver_capabilities"}}
          - name: LD_LIBRARY_PATH
            value: {{ index $module "envconfig" "ld_library_path"}}
          {{ end }}
        resources:
{{ index $module "resources" | toYaml | indent 10 }}
        livenessProbe:
          httpGet:
            path: /.well-known/live
            port: 8080
          initialDelaySeconds: {{ index $module "livenessProbe" "initialDelaySeconds" }}
          periodSeconds: {{ index $module "livenessProbe" "periodSeconds" }}
          timeoutSeconds: {{ index $module "livenessProbe" "timeoutSeconds" }}
        readinessProbe:
          httpGet:
            path: /.well-known/ready
            port: 8080
          initialDelaySeconds: {{ index $module "readinessProbe" "initialDelaySeconds" }}
          periodSeconds: {{ index $module "readinessProbe" "periodSeconds" }}
      {{- with index $module "nodeSelector" | default .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with index $module "affinity" | default (include "affinity" . | fromYaml) }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with index $module "tolerations" | default .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clip-inference
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-clip-inference
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{ end }}
