{{- /* Create forwardAuth Middleware only if ingress is enabled AND either HTTP or gRPC auth is enabled */}}
{{- if and .Values.ingress.enabled (or .Values.ingress.auth.enabled .Values.ingress.grpc.auth.enabled) .Values.ingress.forwardAuth.address }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-headers
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "weaviate.fullname" . }}
    helm.sh/chart: {{ include "weaviate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  headers:
    customRequestHeaders:
      Authorization: ""  # Empty value removes header
      Cookie: ""
{{- end }} 