{{- if (index .Values.clusterApi.basicAuth.secret.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterApi.basicAuth.secret.name }}
type: kubernetes.io/basic-auth
data:
{{- ( include "cluster_api.secret" . ) | indent 2 -}}
{{- end }}
