apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: weaviate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
