apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weaviate-persistence-data
  labels:
    app: weaviate
spec:
  accessModes:
    # Only using one replication so far.
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
