{{ if .Values.grpcService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grpc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.grpcService.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.grpcService.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    {{- range .Values.grpcService.ports }}
    - {{ toYaml . | indent 6 | trim }}
      targetPort: 50051
    {{- end }}
{{ if eq .Values.grpcService.type "ClusterIP" -}}
  {{ if .Values.grpcService.clusterIP }}
  clusterIP: {{ .Values.grpcService.clusterIP }}
  {{ end }}
{{ end }}
{{ if eq .Values.grpcService.type "LoadBalancer" -}}
  {{- if gt (len .Values.grpcService.loadBalancerSourceRanges) 0 }}
  loadBalancerSourceRanges:
    {{- range $_, $sourceRange := .Values.grpcService.loadBalancerSourceRanges }}
    - {{ $sourceRange }}
    {{ end -}}
  {{- end -}}
{{- end }}
{{ end }}
