{{- if and .Values.mcpService.enabled .Values.mcpService.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: weaviate-mcp-config
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  mcp-config.yaml: |-
    {{ .Values.mcpService.config | toYaml | nindent 4 }}
{{- end }}
