name: Upstream to PR

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  autoupdate:
    uses: neuro-inc/reuse/.github/workflows/auto-pr.yaml@master
    with:
      upstream_repository: https://github.com/weaviate/weaviate-helm
      upstream_tag_regex: 'v\d+\..*'
      team_reviewers: 'mlops'
    secrets:
      personal_access_token: ${{ secrets.GH_AUTO_PR }}
